// ============================================
//  DATA - Characters, Items, Missions
//  js/data.js
// ============================================

'use strict';

// ── CHARACTER DATABASE ──
const CharacterData = {

  runners: {
    oggy: {
      id: 'oggy',
      name: 'Oggy',
      type: 'cat',
      color: '#4A90D9',
      bgGrad: 'linear-gradient(135deg,#4A90D9,#1565C0)',
      price: 0,
      ability: 'Balanced Runner',
      desc: 'The lovable blue cat. Well rounded stats.',
      // Stat multipliers (1.0 = default)
      speedMult:   1.0,
      jumpMult:    1.0,
      magnetMult:  1.0,
      coinMult:    1.0,
      // Hitbox scale (1.0 = default)
      hitboxScale: 1.0,
      // Special ability
      special: null,
      // Sprite frames path pattern
      // You add PNG files at sprites/runners/oggy/run0.png etc.
      spritePath: 'sprites/runners/oggy',
      spriteFrames: { run: 6, jump: 1, slide: 1, fall: 1 },
      // Fallback draw color if no sprite loaded
      fallbackColor: '#4A90D9',
      fallbackBelly: '#87CEEB',
    },

    jack: {
      id: 'jack',
      name: 'Jack',
      type: 'cat',
      color: '#4CAF50',
      bgGrad: 'linear-gradient(135deg,#4CAF50,#1B5E20)',
      price: 1500,
      ability: 'Super Jump',
      desc: 'Buff green cat. 35% higher jumps!',
      speedMult:   0.92,
      jumpMult:    1.35,
      magnetMult:  0.85,
      coinMult:    1.0,
      hitboxScale: 1.05,
      special: 'superJump',
      spritePath: 'sprites/runners/jack',
      spriteFrames: { run: 6, jump: 1, slide: 1, fall: 1 },
      fallbackColor: '#4CAF50',
      fallbackBelly: '#81C784',
    },

    bob: {
      id: 'bob',
      name: 'Bob',
      type: 'cat',
      color: '#FF9800',
      bgGrad: 'linear-gradient(135deg,#FF9800,#E65100)',
      price: 2000,
      ability: 'Coin Magnet+',
      desc: 'Chubby cat. 60% wider coin pull!',
      speedMult:   0.88,
      jumpMult:    0.9,
      magnetMult:  1.6,
      coinMult:    1.0,
      hitboxScale: 1.1,
      special: 'wideMagnet',
      spritePath: 'sprites/runners/bob',
      spriteFrames: { run: 6, jump: 1, slide: 1, fall: 1 },
      fallbackColor: '#FF9800',
      fallbackBelly: '#FFB74D',
    },

    olivia: {
      id: 'olivia',
      name: 'Olivia',
      type: 'cat',
      color: '#E91E63',
      bgGrad: 'linear-gradient(135deg,#E91E63,#880E4F)',
      price: 3000,
      ability: 'Speed Dash',
      desc: 'Elegant pink cat. 15% faster speed!',
      speedMult:   1.15,
      jumpMult:    1.0,
      magnetMult:  1.0,
      coinMult:    1.0,
      hitboxScale: 0.92,
      special: 'speedBoost',
      spritePath: 'sprites/runners/olivia',
      spriteFrames: { run: 6, jump: 1, slide: 1, fall: 1 },
      fallbackColor: '#E91E63',
      fallbackBelly: '#F48FB1',
    },

    marky: {
      id: 'marky',
      name: 'Marky',
      type: 'roach',
      color: '#7E57C2',
      bgGrad: 'linear-gradient(135deg,#7E57C2,#311B92)',
      price: 2500,
      ability: 'Tiny Hitbox',
      desc: 'Cockroach with tiny hitbox. Hard to hit!',
      speedMult:   1.08,
      jumpMult:    1.08,
      magnetMult:  0.9,
      coinMult:    1.0,
      hitboxScale: 0.65,
      special: 'smallHitbox',
      spritePath: 'sprites/runners/marky',
      spriteFrames: { run: 6, jump: 1, slide: 1, fall: 1 },
      fallbackColor: '#7E57C2',
      fallbackBelly: '#9575CD',
    },

    joey: {
      id: 'joey',
      name: 'Joey',
      type: 'roach',
      color: '#5C6BC0',
      bgGrad: 'linear-gradient(135deg,#5C6BC0,#1A237E)',
      price: 2500,
      ability: 'Double Coins',
      desc: 'Greedy cockroach. All coins worth 2×!',
      speedMult:   1.0,
      jumpMult:    1.0,
      magnetMult:  1.0,
      coinMult:    2.0,
      hitboxScale: 1.0,
      special: 'doubleCoins',
      spritePath: 'sprites/runners/joey',
      spriteFrames: { run: 6, jump: 1, slide: 1, fall: 1 },
      fallbackColor: '#5C6BC0',
      fallbackBelly: '#7986CB',
    },
  },

  chasers: {
    dee_dee: {
      id: 'dee_dee',
      name: 'Dee Dee',
      type: 'roach',
      color: '#8BC34A',
      bgGrad: 'linear-gradient(135deg,#8BC34A,#33691E)',
      price: 0,
      ability: 'Standard Chase',
      desc: 'The lead cockroach. Standard chasing.',
      chaseSpdMult: 1.0,
      spritePath: 'sprites/chasers/dee_dee',
      spriteFrames: { run: 6 },
      fallbackColor: '#8BC34A',
    },

    marky_chaser: {
      id: 'marky_chaser',
      name: 'Marky',
      type: 'roach',
      color: '#7E57C2',
      bgGrad: 'linear-gradient(135deg,#7E57C2,#311B92)',
      price: 1000,
      ability: 'Sneaky Chaser',
      desc: 'Unpredictable lane-switching chaser!',
      chaseSpdMult: 1.08,
      spritePath: 'sprites/chasers/marky',
      spriteFrames: { run: 6 },
      fallbackColor: '#7E57C2',
    },

    joey_chaser: {
      id: 'joey_chaser',
      name: 'Joey',
      type: 'roach',
      color: '#5C6BC0',
      bgGrad: 'linear-gradient(135deg,#5C6BC0,#1A237E)',
      price: 1000,
      ability: 'Hungry Chaser',
      desc: 'Motivated by food. Never gives up!',
      chaseSpdMult: 0.98,
      spritePath: 'sprites/chasers/joey',
      spriteFrames: { run: 6 },
      fallbackColor: '#5C6BC0',
    },

    oggy_chaser: {
      id: 'oggy_chaser',
      name: 'Oggy',
      type: 'cat',
      color: '#4A90D9',
      bgGrad: 'linear-gradient(135deg,#4A90D9,#1565C0)',
      price: 5000,
      ability: 'Cat Rage Chase',
      desc: 'Oggy is FURIOUS. Role reversal!',
      chaseSpdMult: 1.05,
      spritePath: 'sprites/chasers/oggy',
      spriteFrames: { run: 6 },
      fallbackColor: '#4A90D9',
    },

    jack_chaser: {
      id: 'jack_chaser',
      name: 'Jack',
      type: 'cat',
      color: '#4CAF50',
      bgGrad: 'linear-gradient(135deg,#4CAF50,#1B5E20)',
      price: 5000,
      ability: 'Muscle Chase',
      desc: 'Jack is the fastest chaser!',
      chaseSpdMult: 1.15,
      spritePath: 'sprites/chasers/jack',
      spriteFrames: { run: 6 },
      fallbackColor: '#4CAF50',
    },
  },

  getRunner(id)    { return this.runners[id]; },
  getChaser(id)    { return this.chasers[id]; },
  allRunners()     { return Object.values(this.runners); },
  allChasers()     { return Object.values(this.chasers); },
};


// ── SHOP ITEMS ──
const ShopData = {
  powerups: [
    { id:'magnet',    name:'Coin Magnet',  icon:'🧲', desc:'Attract nearby coins',      price:0,    dur:8  },
    { id:'shield',    name:'Shield',       icon:'🛡️', desc:'Survive one crash',         price:800,  dur:15 },
    { id:'x2score',   name:'Score x2',     icon:'⭐', desc:'Double your score',         price:1200, dur:8  },
    { id:'jetpack',   name:'Jetpack',      icon:'🚀', desc:'Fly over everything',        price:2000, dur:6  },
    { id:'giant',     name:'Giant Mode',   icon:'🦖', desc:'Smash all obstacles',       price:2500, dur:5  },
    { id:'invisible', name:'Ghost Mode',   icon:'👻', desc:'Pass through obstacles',    price:3000, dur:5  },
    { id:'timeslow',  name:'Time Slow',    icon:'⏳', desc:'Slow down the world',       price:3500, dur:4  },
    { id:'coinrain',  name:'Coin Rain',    icon:'🌧️', desc:'Coins pour from the sky',  price:4000, dur:5  },
  ],

  themes: [
    { id:'city',    name:'City',       icon:'🏙️', desc:"Oggy's neighborhood",  price:0     },
    { id:'beach',   name:'Beach',      icon:'🏖️', desc:'Sunny seaside run',    price:1500  },
    { id:'space',   name:'Space',      icon:'🌌', desc:'Outer space adventure', price:3000  },
    { id:'jungle',  name:'Jungle',     icon:'🌴', desc:'Wild jungle path',      price:2000  },
    { id:'snow',    name:'Snow',       icon:'❄️', desc:'Winter wonderland',     price:2500  },
    { id:'night',   name:'Night City', icon:'🌃', desc:'Neon night run',        price:3500  },
  ],

  boosts: [
    { id:'headstart',  name:'Head Start',    icon:'🏁', desc:'+500m head start',    price:500,  consumable:true },
    { id:'coinboost',  name:'Coin Boost',    icon:'💰', desc:'+50% coins this run', price:400,  consumable:true },
    { id:'scoreboost', name:'Score Boost',   icon:'📈', desc:'+50% score this run', price:600,  consumable:true },
    { id:'extralife',  name:'Extra Life',    icon:'❤️', desc:'Continue after crash', price:800, consumable:true },
    { id:'luckystart', name:'Lucky Start',   icon:'🍀', desc:'Start with shield',   price:300,  consumable:true },
  ],
};


// ── MISSIONS ──
const MissionData = [
  {
    id: 'coins100',
    title: 'Coin Collector',
    desc: 'Collect 100 coins in one run',
    icon: '🪙',
    iconBg: 'linear-gradient(135deg,#FFD700,#FFA000)',
    type: 'coins_run',
    target: 100,
    reward: 200,
  },
  {
    id: 'dist2000',
    title: 'Marathon Runner',
    desc: 'Run 2000m in one run',
    icon: '🏃',
    iconBg: 'linear-gradient(135deg,#4facfe,#00f2fe)',
    type: 'distance_run',
    target: 2000,
    reward: 350,
  },
  {
    id: 'score5000',
    title: 'Score Master',
    desc: 'Score 5000 points',
    icon: '⭐',
    iconBg: 'linear-gradient(135deg,#667eea,#764ba2)',
    type: 'score_best',
    target: 5000,
    reward: 500,
  },
  {
    id: 'play10',
    title: 'Play 10 Games',
    desc: 'Complete 10 runs',
    icon: '🎮',
    iconBg: 'linear-gradient(135deg,#f093fb,#f5576c)',
    type: 'games_total',
    target: 10,
    reward: 400,
  },
  {
    id: 'coins_total1000',
    title: 'Coin Hoarder',
    desc: 'Collect 1000 total coins ever',
    icon: '💰',
    iconBg: 'linear-gradient(135deg,#fa709a,#fee140)',
    type: 'coins_total',
    target: 1000,
    reward: 800,
  },
  {
    id: 'dist5000',
    title: 'Speed Demon',
    desc: 'Run 5000m in one run',
    icon: '⚡',
    iconBg: 'linear-gradient(135deg,#43e97b,#38f9d7)',
    type: 'distance_run',
    target: 5000,
    reward: 1200,
  },
  {
    id: 'play50',
    title: 'Veteran Runner',
    desc: 'Play 50 total games',
    icon: '🎖️',
    iconBg: 'linear-gradient(135deg,#667eea,#764ba2)',
    type: 'games_total',
    target: 50,
    reward: 2000,
  },
  {
    id: 'score20000',
    title: 'Legend',
    desc: 'Score 20000 points in one run',
    icon: '🏆',
    iconBg: 'linear-gradient(135deg,#FFD700,#FF6F00)',
    type: 'score_best',
    target: 20000,
    reward: 5000,
  },
];


// ── OBSTACLE TYPES ──
const ObstacleTypes = [
  {
    id:      'barrier',
    label:   'Road Barrier',
    w:       38,
    h:       42,
    color:   '#D32F2F',
    color2:  '#B71C1C',
    stripe:  '#FFD700',
    action:  'jump',   // player must: jump / slide / dodge
    spritePath: 'sprites/obstacles/barrier.png',
  },
  {
    id:      'car',
    label:   'Parked Car',
    w:       52,
    h:       32,
    color:   '#1565C0',
    color2:  '#0D47A1',
    stripe:  null,
    action:  'jump',
    spritePath: 'sprites/obstacles/car.png',
  },
  {
    id:      'truck',
    label:   'Truck',
    w:       60,
    h:       48,
    color:   '#37474F',
    color2:  '#263238',
    stripe:  null,
    action:  'dodge',  // must switch lane
    spritePath: 'sprites/obstacles/truck.png',
  },
  {
    id:      'beam',
    label:   'Low Beam',
    w:       58,
    h:       18,
    color:   '#F57F17',
    color2:  '#E65100',
    stripe:  '#FFF',
    action:  'slide',  // player must slide
    elevated: true,
    yOffset: 30,
    spritePath: 'sprites/obstacles/beam.png',
  },
  {
    id:      'cone',
    label:   'Traffic Cone',
    w:       24,
    h:       32,
    color:   '#FF6F00',
    color2:  '#E65100',
    stripe:  '#FFF',
    action:  'jump',
    spritePath: 'sprites/obstacles/cone.png',
  },
  {
    id:      'box',
    label:   'Crate',
    w:       36,
    h:       36,
    color:   '#795548',
    color2:  '#4E342E',
    stripe:  null,
    action:  'jump',
    spritePath: 'sprites/obstacles/box.png',
  },
  {
    id:      'hydrant',
    label:   'Fire Hydrant',
    w:       24,
    h:       36,
    color:   '#C62828',
    color2:  '#B71C1C',
    stripe:  '#FFD700',
    action:  'jump',
    spritePath: 'sprites/obstacles/hydrant.png',
  },
  {
    id:      'bench',
    label:   'Park Bench',
    w:       52,
    h:       28,
    color:   '#5D4037',
    color2:  '#3E2723',
    stripe:  null,
    action:  'jump',
    spritePath: 'sprites/obstacles/bench.png',
  },
];